### ISSUE TITLE
Unable to make the Asset controller working with version ~3.0

### ISSUE THREAD

**Issue by codedumper** [DarkaOnLine/SwaggerLume#28] opened 2017-09-01 17:49 UTC
Installed packages :
        "php": ">=5.6.4",
        "laravel/lumen-framework": "5.4.*",
        "vlucas/phpdotenv": "2.4.0",
        "illuminate/redis": "5.4.*",
        "palanik/lumen-cors": "dev-master",
        "giggsey/libphonenumber-for-php": "^8.8",
        "darkaonline/swagger-lume": "~3.0"

withFacades is active, Service provider is registered, swaggerlume is configured in bootstrap.
All seems working except the controller with assets :
http://localhost:8000/swagger-ui-assets/swagger-ui.css return a templated page with : 
The requested resource /swagger-ui-assets/swagger-ui.css was not found on this server.
Same thing with js files.

**Comment by codedumper** [comment] 2017-09-01 20:56
Back to version 2.0, all is working fine. i suspect i misunderstood the way to install/publidh swagger-ui bundle.

**Comment by DarkaOnLine** [comment] 2017-09-02 10:47
@codedumper I just tried fresh installation of lumen again and everything work's fine.

It looks like something wrong with routing on your side. It looks like you are running php server, could you try running your app on apache/nginx ?

**Comment by matrixn** [comment] 2017-09-04 23:08
I am having the same issue, is there some problem when migrating from 2.0 to 3.0 with routes? apparently the assets => /swagger-ui-assets route is not working. Should it be registered automatically or i have to create the route manually? if so where should the assets be generated as i haven't found any assets folder.

**Comment by DarkaOnLine** [comment] 2017-09-05 07:05
@matrixn Did you deleted your old `swagger-lume.php` config file and published the new one?

Yes, routes are registered automatically.

Assets now are a dependency of "swagger-api/swagger-ui", so we are now always up to  date with the latest swagger-ui.

**Comment by matrixn** [comment] 2017-09-05 13:32
Yes, i deleted. I did some investigations and i believe that the reason for not working assets routes is dingo api to be blamed. It seems that is seeing the route is handled through the dingo api files. however if i removed the {asset} part of the route in route.php of the package and the route worked just fine and hitted the SwaggerLumeAssetController index function but is not hitting the index function of that controller if the file (e.g. swagger-ui.css) is accessed and is going through the dingo/api routes... i still haven't found a workaround ... yet

here is my composer info packages that i am using

https://paste.ee/p/DXILA

**Comment by DarkaOnLine** [comment] 2017-09-05 13:42
can you try registering SwaggerLume service provider after Dingo?

**Comment by matrixn** [comment] 2017-09-05 16:49
Tried that allready...same output.. :(

**Comment by codedumper** [comment] 2017-09-07 20:20
I tried to add log on SwaggerLumeAssetController but this route was never reached. 
It works like route was never register. I've done all the migration process, restarted a new fresh config and regenerate docs. All seems fine except routing to assets.

I use php -S localhost:8000 -t public

**Comment by codedumper** [comment] 2017-09-07 20:21
I also tried to remove other services and class registered. Same result.

**Comment by codedumper** [comment] 2017-09-07 23:07
@DarkaOnLine I can config. I trace the flow with XDebug and the route is not used to load the assets. I can also confirm the routes are registered. (/swagger-ui-assets/{asset})

@2nd test : 
cp -a vendor/swagger-api/swagger-ui/dist public/swagger-ui-assets
And, it works. (as workaround)

**Comment by matrixn** [comment] 2017-09-07 23:23
Well, copying assets folder to public is quite over the head  early scratching :))

There is definitely something wrong with the route registration process on lumen I think. I have postponed my debugging till I'll be back from holidays.

**Comment by DarkaOnLine** [comment] 2017-09-08 05:18
I jus tested fresh install.

First apache host http://lumen.dev - everything is working
Second `php -S localhost:8000 -t public` - assets could not be found.  🎉 

So the problem is that routes are not working with php server. I will try to look into it but I do not have much experience with it :(

**Comment by DarkaOnLine** [comment] 2017-09-08 05:31
5 minutes on StackOverflow and I think I found solutions.

PHP build in server does not support url_rewrite, so you need to implement it by your self. And it's simple as:

- create `public/rewrite.php` file:

```php
<?php

if (preg_match('/\.(?:png|jpg|jpeg|gif)$/', $_SERVER["REQUEST_URI"])) {
    return false;
} else {
    include __DIR__ . '/index.php';
}
```

- run from command line:

`php -S localhost:8888 rewrite.php`



🎉  it should work :))))

Let me now about the results.

**Comment by codedumper** [comment] 2017-09-08 11:42
@matrixn it was a way to demonstrate the route isn't called.

@DarkaOnLine I was on it too. It works. Last time, i use a built-in server. thanks for the workaround. this is the last time i use a built-in something :)

**Comment by DarkaOnLine** [comment] 2017-09-08 12:16
@codedumper thanks for testing and confirmation. Closing this 🔐

**Closed by DarkaOnLine** 2017-09-08 12:16 UTC

**Comment by rbruhn** [comment] 2017-09-23 23:30
@matrixn Did you ever figure a way around your problem? I'm using Dingo API as well and tried various things that didn't work.
